void LEDCONTROL_SETUP(){
  const int LEDCONTROL_PINARRAY[] = {6, 7, 8, 9, 10, 11, 12, 13};
  const int LEDCONTROL_NUMBEROFPINS = 8;

}

int[] LEDCONTROL_GET_PINARRAY(){
  return LEDCONTROL_PINARRAY;
}

void 