int LEDCONTROL_GET_NUMBEROFLEDS(){
  const int LEDCONTROL_NUMBEROFLEDS = 8;
}

int LEDCONTROL_GET_PINARRAY(){
  const int LEDCONTROL_PINARRAY[6, 7, 8, 9, 10, 11, 12, 13];
  return LEDCONTROL_PINARRAY;
}

void LEDCONTROL_SETUP(int LEDCONTROL_NUMBEROFLEDS){
  for (int i = 0; i < LEDCONTROL_NUMBEROFLEDS; i++)
  pinMode(LEDCONTROL_PINARRAY[i], OUTPUT);
}

void LEDCONTROL_ON(int pin){
  digitalWrite(pin, HIGH);
}

void LEDCONTROL_OFF(int pin){
  digitalWrite(pin, LOW);
}